name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - main
    #tags:
    #  - act-v*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Deploy # 只提交到github
        uses: JamesIves/github-pages-deploy-action@releases/v2 # 作用：将项目构建和部署到github
        env: # 设置环境变量
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }} # toKen私密变量
          BASE_BRANCH: main # 要部署的文件夹所在的分支.
          BRANCH: gh-pages # 部署到的分支
          FOLDER: docs/.vuepress/dist # 要部署的文件夹.
          BUILD_SCRIPT: npm install && npm run build && cd docs/.vuepress/dist && echo 'myhost.com' > CNAME && cd - # 部署前要执行的命令（记得cd进入某个目录后，后面要cd -退回开始的目录）
      
      # - name: Build && Deploy #同时部署到github和coding
      #   env: # 设置环境变量
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }} # toKen私密变量
      #     CODING_TOKEN: ${{ secrets.CODING_TOKEN }}
      #   run: npm install && npm run deploy
