name: CI_PAGES

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ '16' ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' 

      - name: Make Category
        run: | 
          cd blog_raw && python scripts/make_category.py && cd ..

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Build vuepress-theme-vdoing
        run: |
          cd vuepress-theme-vdoing 
          npm install && npm run build_base_blog
          cd ..

      - name: Deploy # 只提交到github
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with: 
          token: ${{ secrets.ACCESS_TOKEN }} # GitHub Token
          branch: gh-pages # 部署到的分支
          folder: vuepress-theme-vdoing/docs/.vuepress/dist # 要部署的文件夹.
